### ISSUE TITLE
Tag last committer of a branch in opened issues

### ISSUE THREAD

**Issue by deniszgonjanin** [crs-k/stale-branches#280]
**Is your feature request related to a problem? Please describe.**
The issues the stale branch action opens are prone to get lost in repos with many committers. Because nobody is tagged on the issue, the people who may care about the branch getting deleted may miss the issue entirely.

**Describe the solution you'd like**
Tagging the last committer of a stale branch alerts the relevant person that their work may be deleted. It also implicitly assigns ownership to an issue, reducing the chance of orphaned issues littering the repo.

Thank you for making this action ✌️

**Comment by crs-k** [comment]
Great idea, I am going to add it as input option and default it to false. Some of the messier repos we've used this on will close 20 branches per run due to the age of branches exceeding the days-before-delete threshold. We would not want to alert users in that case.

I can look at enhancing this later to ignore those cases.
